version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.4
    commands:
      - echo "Installing Composer..."
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - composer install --no-interaction --prefer-dist

  build:
    commands:
        - echo "Running Yii2 migrations..."
        - ./yii migrate --interactive=0

artifacts:
  files:
    - "**/*"
    - "!vendor/**/*"
    - "!tests/**/*"
